tabela_brasileirao = ('Botafogo','Palmeiras','Fortaleza','Flamengo','São Paulo','Internacional','Bahia','Cruzeiro','Atlético-MG','Vasco de Gama','Grêmio','Criciúma','Bragantino','Juventude','Athletico-PR','Fluminense','EC Vitória','Corinthians','Cuiabá','Atlético-GO')
print('\033[1;33m=\033[m'*60)
print(f'\nLista de times do Brasileirão : {tabela_brasileirao}\n')
print('\033[1;33m=\033[m'*60)
print(f'\nOs 5 primeiros colocados são {tabela_brasileirao[0:5]}\n')
print('\033[1;33m=\033[m'*60)
print(f'\nOs 4 últimos são {tabela_brasileirao[16:21]}\n')
print('\033[1;33m=\033[m'*60)
print('\nO Cruzeiro esta na {}° posição\n'.format(tabela_brasileirao.index('Atlético-MG')))
print('\033[1;33m=\033[m'*60)
